# App Info
ios_app_id                                : 1522666671                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : GetBetter
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Удобное приложение для учёта личной эффективности по принципу "колеса жизненного баланса".

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Artur Islamgulov
your_link                                 : https://www.notion.so/Artur-Islamgulov-72c202cd6d954fce9dc0f00cba8270d6
your_city                                 : Kazan
email_address                             : artur.islamgulov@gmail.com
facebook_username                         : arturisart                                          
instagram_username                        : arturisart
twitter_username                          : zavtra_v_Texas
github_username                           : stoletnaedine
youtube_username                          : zavtravTexas



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Понятная инфографика
    description                           : Наглядная круговая диаграмма, показывающая прогресс в восьми сферах жизни (работа, здоровье, творчество, отношения, отдых, духовность, финансы, окружение).
    fontawesome_icon_name                 : chart-bar

  - title                                 : Ежедневные напоминания
    description                           : GetBetter может напоминать вам записывать итоги дня, чтобы прокачивать сферы. Включить уведомления можно в настройках приложения.
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Дневник важных событий
    description                           : Вы можете вести дневник событий своей жизни с фотографиями и вспоминать, что сделало вас лучше.
    fontawesome_icon_name                 : comments

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#8643f9"

app_title_color                           : "#000"
app_price_color                           : "#000"
app_description_color                     : "#000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#8643f9"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
